### ISSUE TITLE
the length needs to be longer. camera images are 614400 bytes long

### ISSUE THREAD

**Issue by brycedcarter** [PetRover/rWifi#19]
https://github.com/PetRover/rWifi/blob/88f793910a3dbb6826f51c794fd85c6972754c35/wifi.cpp#L458

**Comment by ajbezreh** [comment]
We're not going to be able to send single transmissions with that much....

I looked into it a bit and it says the ABSOLUTE max that udp can send is 65507 although standard use of UDP doesn't send more than 512 at a time. 

hmmm... best way to fix this? Each image is 614400 bytes long? So we'll have to break them apart, send them, and piece them back together?

**Comment by ajbezreh** [comment]
Fixed a while ago
