### ISSUE TITLE
apparently we are getting cbData with UID that is not in chunkAccumulator

### ISSUE THREAD

**Issue by brycedcarter** [PetRover/rWifi#23]
chunkBox is being set to a null pointer which causes call to "getIsFull" to fail

please fix ASAP

![image](https://cloud.githubusercontent.com/assets/3966935/11454741/a44efe8a-9606-11e5-9da8-8b3fba7b0750.png)

**Comment by ajbezreh** [comment]
Should now ignore CbDatas if the associated CbHeader was not received
