### ISSUE TITLE
Implement connection::connect and connection::disconnect

### ISSUE THREAD

**Issue by ajbezreh** [PetRover/rWifi#3]
Figure out how to use the socket library we pick to set up a connection and disconnect as well. To close this issue, have the implementation written in rWifi.c

**Comment by ajbezreh** [comment]
connect:
returns - pointer to the connection 
parameters - whatever is needed according to functions below to connect
functions: uses these functions:
     int socket(int domain, int type, int protocol); //creates unbound socket. creates file descriptor that we can use to reference socket to perform actions on it later  
     int connect(int socket, const struct sockaddr *address,socklen_t address_len);

disconnect
returns - affirmation that socket was disconnected
parameters - potentially none - parameters of shutdown function should be stored as private in the connection class (ex: socket = file descriptor of the socket)
functions - uses int shutdown(int socket, int how);
    hard-code "how" to SHUT_RDWR - Disables further send and receive operations. - other options for "how" aren't as useful to us

**Comment by ajbezreh** [comment]
Obviously haven't tested the code. But finished my first pass at implementing it. Will need a second look. About 90% sure it compiles =p

**Comment by brycedcarter** [comment]
why only 90% that it compiles?

**Comment by ajbezreh** [comment]
HAHAH. I took care of the errors in my code that appeared when I compiled
but there were errors in rtest that I didn't look into (leaving for a
retreat right now). So they're probably unrelated since I haven't touched
that file that I remember. So I just can't confirm that I had a full
successful compilation and others in mine weren't going to come up.

**Comment by brycedcarter** [comment]
it all compiles just fine on mine (including your stuff :) )... what issues is rTests having on yours
